[E 240126 20:39:10 algo:48] Historic Api failed: Couldn't parse the JSON response received from the server: b''
    Traceback (most recent call last):
      File "C:\Users\soura.DESKTOP-G4H1BGN\AppData\Local\Programs\Python\Python312\Lib\site-packages\SmartApi\smartConnect.py", line 196, in _request
        data = json.loads(r.content.decode("utf8"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\soura.DESKTOP-G4H1BGN\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
        return _default_decoder.decode(s)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\soura.DESKTOP-G4H1BGN\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\soura.DESKTOP-G4H1BGN\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "e:\Projects\MyTools\TradeAlgo\algo.py", line 46, in <module>
        print(smartApi.getCandleData(historicParam))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\soura.DESKTOP-G4H1BGN\AppData\Local\Programs\Python\Python312\Lib\site-packages\SmartApi\smartConnect.py", line 430, in getCandleData
        getCandleDataResponse=self._postRequest("api.candle.data",historicDataParams)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\soura.DESKTOP-G4H1BGN\AppData\Local\Programs\Python\Python312\Lib\site-packages\SmartApi\smartConnect.py", line 228, in _postRequest
        return self._request(route, "POST", params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\soura.DESKTOP-G4H1BGN\AppData\Local\Programs\Python\Python312\Lib\site-packages\SmartApi\smartConnect.py", line 199, in _request
        raise ex.DataException("Couldn't parse the JSON response received from the server: {content}".format(
    SmartApi.smartExceptions.DataException: Couldn't parse the JSON response received from the server: b''
[E 240126 20:39:27 algo:48] Historic Api failed: Couldn't parse the JSON response received from the server: b''
    Traceback (most recent call last):
      File "C:\Users\soura.DESKTOP-G4H1BGN\AppData\Local\Programs\Python\Python312\Lib\site-packages\SmartApi\smartConnect.py", line 196, in _request
        data = json.loads(r.content.decode("utf8"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\soura.DESKTOP-G4H1BGN\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
        return _default_decoder.decode(s)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\soura.DESKTOP-G4H1BGN\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\soura.DESKTOP-G4H1BGN\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "e:\Projects\MyTools\TradeAlgo\algo.py", line 46, in <module>
        print(smartApi.getCandleData(historicParam))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\soura.DESKTOP-G4H1BGN\AppData\Local\Programs\Python\Python312\Lib\site-packages\SmartApi\smartConnect.py", line 430, in getCandleData
        getCandleDataResponse=self._postRequest("api.candle.data",historicDataParams)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\soura.DESKTOP-G4H1BGN\AppData\Local\Programs\Python\Python312\Lib\site-packages\SmartApi\smartConnect.py", line 228, in _postRequest
        return self._request(route, "POST", params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\soura.DESKTOP-G4H1BGN\AppData\Local\Programs\Python\Python312\Lib\site-packages\SmartApi\smartConnect.py", line 199, in _request
        raise ex.DataException("Couldn't parse the JSON response received from the server: {content}".format(
    SmartApi.smartExceptions.DataException: Couldn't parse the JSON response received from the server: b''
